---

- name: Download composer.phar
  get_url:
    url: https://getcomposer.org/installer
    dest: /root/composer-setup.php
    mode: '0440'

- name: Install composer
  shell: "/usr/bin/php composer-setup.php --install-dir=/usr/bin --filename=composer"
  args:
    executable: /bin/bash
    chdir: "/root"
