---

- name: Download composer.phar
  get_url:
    url: https://getcomposer.org/installer -o composer-setup.php
    dest: ~
    mode: '0440'

- name: Generate SSL certificate
  shell: "/usr/bin/php composer-setup.php --install-dir=/usr/bin --filename=composer"
