---
- include: define-variables.yml
- include: setup.yml

- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: "{{ apache_service }}"
    state: "started"
    enabled: yes

# Cette tâche fait appel à un autre fichier de configuration pour installer PHP. Elle est exécutée uniquement si la variable php_install est à vraie (par défaut, elle est à faux)
- name: Install php packages
  include: "php-{{ ansible_os_family }}-install.yml"
  when: php_install|default(False)|bool
