---
# tasks file for apache
- name: "Ensure Apache is installed on Debian."
  apt:
    name: "{{ item }}"
    state: present
    update_cache: "{{ update_cache }}" 
  with_items: "{{ apache_packages }}"

- name: "Enable mod_rewrite"
  apache2_module:
    state: present
    name: rewrite 
  changed_when: yes
  notify: [ "{{ ansible_os_family }} restart apache2" ]
