---
# tasks file for apache
- name: "Ensure Apache is installed on Debian."
  apt:
    name: "{{ item }}"
    state: present
    update_cache: "{{ update_cache }}" 
  with_items: "{{ apache_packages }}"

- name: "Enable mod_rewrite"
  apache2_module:
    state: present
    name: rewrite 
  changed_when: yes
  notify: [ "restart apache2" ]

# Cette tâche fait appel à un autre fichier de configuration pour installer PHP. Elle est exécutée uniquement si la variable php_install est à vraie (par défaut, elle est à faux)
- name: "install php packages"
  include: "php-install.yml"
  when: php_install|default(False)|bool
