---
# tasks file for confpostgresql

- name: Assign privileges
  postgresql_user:
    name: "{{ project_user }}"
    password: "{{ db_password }}"
    priv: "ALL/{{ project_name }}:ALL"
    db: postgres
    state: present

- name: Create database
  postgresql_db:
    name: "{{ project_name }}"
    owner: "{{ project_user }}"
    state: present

