---
# tasks file for mysql
- name: Install mysql and python utilities
  apt:
    name: "mysql-server,python3-pip,libmysqlclient-dev"
    state: present
    update_cache: "{{ update_cache }}"

- name: Install python module
  pip:
    name: "configparser,mysql-connector,PyMySQL"
    state: present

- name: Enable and start mysql
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes
