---
# tasks file for mysql
- name: "install mysql and python utilities"
  apt:
    name: "mysql-server,python3-pip,libmysqlclient-dev"
    state: present
    update_cache: "{{ update_cache }}"

- name: "install python module"
  pip:
    name: "configparser,mysql-connector,PyMySQL"
    state: present

- name: "enable mysql"
  ansible.builtin.service:
    name: mysql
    enabled: yes

- name: "start mysql"
  ansible.builtin.service:
    name: mysql
    state: started
