---
# tasks file for mysql

- name: Install utilities
  apt:
    name: "{{ utilities }}"
    state: present
    update_cache: "{{ update_cache }}" 

- name: Install MySQL
  apt:
    name: "{{ mysql_packages }}"
    state: present
    update_cache: "{{ update_cache }}" 

- name: Set python3.8 as default
  shell: /usr/bin/update-alternatives --set python /usr/bin/python3.8
  args:
    executable: /bin/bash
