---
- name: reload httpd
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: reloaded

- name: Restart firewalld
  ansible.builtin.service:
    name: "firewalld"
    state: restarted
