---
- include: define-variables.yml

# tasks file for confapache
- name: Create the working directory if it does not exist
  ansible.builtin.file:
    path: "{{ working_dir }}"
    state: directory
    mode: "0775"

- name: Clonning the repo
  ansible.builtin.git:
    repo: "{{ git_url }}"
    dest: "{{ working_dir }}"
  when: git_url != "no"

- name: Change file ownership, group and permissions of the working_dir
  ansible.builtin.file:
    path: "{{ working_dir }}"
    owner: "{{ project_user }}"
    group: "{{ apache_user }}"
    mode: "0775"
    recurse: yes    

# if domain_name is set to 'no', it means that Alias will be used
# else domain_name will be used
- name: Setting domain_name 
  set_fact:
    domain_name: "{% if domain_name == 'no' %}{{ project_name }}{% else %}{{ domain_name }}{% endif %}"

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Stop Apache for generating SSL certificat
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: stopped
  when: use_ssl == "yes"

- name: Generate SSL certificate
  shell: "/usr/bin/letsencrypt certonly --standalone --agree-tos -d {{ domain_name }} --email {{ admin_email }} --renew-by-default"
  notify: [ "restart httpd" ]
  when: use_ssl == "yes"
  args:
    executable: /bin/bash
