---
# tasks file for confapache
- name: Create the working directory if it does not exist
  ansible.builtin.file:
    path: "{{ working_dir }}"
    state: directory
    mode: "0775"

- name: Clonning the repo
  ansible.builtin.git:
    repo: "{{ git_url }}"
    dest: "{{ working_dir }}"

# if domain_name is set to 'no', it means that Alias will be used
# else domain_name will be used
- name: Setting domain_name 
  set_fact:
    domain_name: "{% if domain_name == 'no' %}{{ project_name  }}{% else %}{{ domain_name }}{% endif %}"


# if domain_name is set to project_name, it means that Alias template will be used
# else vhost template will be used
- name: Add apache site configuration files.
  template:
    src: "{% if domain_name == project_name %}alias.j2{% else %}vhost.j2{% endif %}"
    dest: "{{ sites_availabe }}/{{ domain_name }}.conf"
    owner: root
    group: root
    mode: '0744'

# - name: Stop apache2 for generating SSL certificat
#   ansible.builtin.service:
#     name: apache2
#     state: stop

# - name: Generate SSL certificate
#   shell: "/usr/bin/letsencrypt certonly --standalone --agree-tos -d {{ domain_name }} --email {{ admin_email }} --renew-by-default"
      
- name: Enable the site
  shell: "/usr/sbin/a2ensite {{ domain_name }}.conf"
  notify: [ "{{ ansible_os_family }} restart apache2" ]

- name: Change file ownership, group and permissions of the working_dir
  ansible.builtin.file:
    path: "{{ working_dir }}"
    owner: "{{ project_user }}"
    group: "www-data"
    mode: "0775"
    recurse: yes
