---

# if domain_name is set to project_name, it means that Alias template will be used
# else vhost template will be used
- name: Add apache site configuration files.
  template:
    src: "{% if domain_name == project_name %}alias.j2{% else %}vhost.j2{% endif %}"
    dest: "{{ sites_availabe }}/{{ domain_name }}.conf"
    owner: root
    group: root
    mode: '0744'
      
- name: Enable the site
  ansible.builtin.file:
    src: "{{ sites_availabe }}/{{ domain_name }}.conf"
    dest: "{{ sites_enabled }}/{{ domain_name }}.conf"
    owner: root
    group: root
    state: link
  notify: ["reload httpd"]