---
# tasks file for confmysql

- name: "create database"
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ project_name }}"
    state: present

- name: "assign privileges"
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ project_user }}"
    host:  localhost
    password: "{{ db_password }}"
    priv: "{{ project_name }}.*:ALL"
    state: present


