---
- name: Include hosts playbook
  import_playbook: host.yml # include the host.yml to ask the target host to which the playbook should be run

- name: Generate letsencrypt certificate
  hosts: dynamically_created_hosts

  vars_prompt:
  - name: domain_name
    prompt: Enter the domain name 
    private: no

  - name: webserver
    prompt: Enter the webserver type [apache|nginx]
    private: no

  - name: update_cache
    prompt: Enter the webserver type [apache|nginx]
    default: "no"
    private: no

  pre_tasks:
    - assert:
        that:
          - domain_name is regex("^(no)|([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$")
          - webserver is regex("apache|nginx|httpd")

  roles:
    - role: "letsencrypt"